### ISSUE TITLE
More complex options for comments

### ISSUE THREAD

**Issue by hawkw** [Marwes/combine-language#3]
Currently, the `comment_start`, `comment_end,` and `comment_line` fields in `LanguageDef` take strings, allowing a single string to be used as the definition for comments. 

It would be nice if these definitions could take parsers, instead, since in some languages, there are multiple ways to denote a comment. For example, in R<sup>6</sup>RS Scheme, a line comment may begin with either `;` or `#;`.

**Comment by Marwes** [comment]
That seems a fair change to make. I just followed parsec which only has strings as well and I wasn't aware of any languages which have multiple way of writing the same comment type.

**Comment by hawkw** [comment]
It's not terribly common, you're right. Another use-case would be if you're writing an interpreter and you want to ignore shebang lines starting with `#!` and your line comments begin with a different sigil.

**Comment by Marwes** [comment]
`#!` could be handled easier without this lib though since it only appears in one place. Just add `optional(string("#!") ...).with(yourparser)` at the entry point of the parser.

I guess the only problem with this change might be how to handled nested comments (if this gets added, Parsec.Token has optionally support for nested comments). I think it should still be alright though.

**Comment by hawkw** [comment]
> `#!` could be handled easier without this lib though since it only appears in one place. 

True, good point.

**Comment by Marwes** [comment]
24c1279cf0fbcb51c293b641e11e0dfa4c153e58 resolves this though it may be good to revisit the implementation since it might not be as efficient as it can be/not generate good error messages.

**Comment by Marwes** [comment]
0.6.0 is on crates.io with this change now.
